services:
  - type: web
    name: castle-marsh-cust-demo
    env: node
    plan: starter
    autoDeploy: true
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm run start
    healthCheckPath: /
    envVars:
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
